name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
# ! Mealplanr Project---------------------------------------------------------------------------------------
    - name: Assign issues and PRs to repo project
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: 'https://github.com/orgs/BHelpful/projects/2'

# ! BHelpful Project---------------------------------------------------------------------------------------
    - name: Assign PRs BHelpful project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event_name == 'pull_request'
      with:
        project: 'https://github.com/orgs/BHelpful/projects/1'
