name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: self-hosted
    name: Assign to One Project
    steps:

# ! Repo Project---------------------------------------------------------------------------------------
    - name: Assign issues to repo project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/BHelpful/Mealplanr-api/projects/1'
