name: Issue Checklist Checker

on: issues

jobs:
  checkIssue:
    name: Check Issue for Incomplete Checklist
    runs-on: ubuntu-latest
    steps:
      - uses: adamzolyak/checklist-checker-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Self hosted deploy server cleanup, should ALWAYS run independent to result
      - name: Cleanup
        if: ${{ always() }}
        run: docker ps -q | xargs -n 1 -P 8 -I {} docker stop {}