name: pivotal-lint
on: [pull_request]

jobs:
  pivotal-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: cleartax/pivotal-lint@master
        name: pivotal-lint
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pivotal-token: ${{ secrets.PIVOTAL_TOKEN }}
          skip-branches: '^(production-release|master|release\/v\d+)$'
          skip-comments: true
          pr-threshold: 1000