on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - master
  pull_request:
      types: [opened, synchronize, reopened]
name: Code Quality Analysis
jobs:
  sonarcloud:
    runs-on: vds2019x11
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    # Self hosted deploy server cleanup, should ALWAYS run independent to result
    - name: Cleanup
      if: ${{ always() }}
      run: docker ps -q | xargs -n 1 -P 8 -I {} docker stop {}